name: 'Container Build and Publish'
description: 'GitHub Action with a pipeline to build, test and publish a container image'
inputs:
  workdir:
    description: "Working directory of bake execution"
    required: false
    default: '.'
  test-targets:
    description: "List of bake targets for testing"
    required: false
    default: 'local'
  dockerhub-username:
    description: 'Username used to log against the Docker registry'
    required: false
    default: ''
  dockerhub-password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
    default: ''
  image-name-filter:
    description: 'Jq filter used to search for the image name'
    required: false
    default: ".target.default.labels.\"org.opencontainers.image.title\""
  image-description-filter:
    description: 'Jq filter used to search for the image description'
    required: false
    default: '.target.default.labels."org.opencontainers.image.description"'
  image-readme-filepath-filter:
    description: 'Jq filter used to search for the image readme filepath'
    required: false
    default: '.target.default.labels["io.boxcutter.image.readme-filepath"]'
    
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Check the Containerfile with hadolint
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        $(git rev-parse --show-toplevel)/bin/lint.sh

    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build locally for testing
      uses: docker/bake-action@v4
      with:
        workdir: ${{ inputs.workdir }}
        targets: ${{ inputs.test-targets }}
        load: true

    - name: Run tests on the image with cinc-auditor
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        $(git rev-parse --show-toplevel)/bin/test.sh

    - name: Debug
      shell: bash
      run: |
        echo "github.event_name = ${{ github.event_name }}"
        
    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Build and push
      uses: docker/bake-action@v4
      with:
        workdir: ${{ inputs.workdir }}
        push: ${{ github.event_name != 'pull_request' }}

    - name: Get the image name
      if: ${{ github.event_name != 'pull_request' }}
      id: image_name
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        json_data="$(docker buildx bake --print 2>/dev/null)"
        echo ${{ inputs.image-name-filter }}
        echo "image_name=$(echo "$json_data" | jq -r "${{ inputs.image-name-filter }}")" >> $GITHUB_ENV
