name: 'Container Build and Publish'
description: 'GitHub Action with a pipeline to build, test and publish a container image'
inputs:
  workdir:
    description: "Working directory of bake execution"
    required: false
    default: '.'
  test-targets:
    description: "List of bake targets for testing"
    required: false
    default: 'local'
  dockerhub-username:
    description: 'Username used to log against the Docker registry'
    required: false
    default: ''
  dockerhub-password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
    default: ''
    
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Check the Containerfile with hadolint
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        $(git rev-parse --show-toplevel)/bin/lint.sh

    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build locally for testing
      uses: docker/bake-action@v4
      with:
        workdir: ${{ inputs.workdir }}
        targets: ${{ inputs.test-targets }}
        load: true

    - name: Run tests on the image with cinc-auditor
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        $(git rev-parse --show-toplevel)/bin/test.sh

    - name: Login to DockerHub
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Build and push
      uses: docker/bake-action@v4
      with:
        workdir: ${{ inputs.workdir }}
        push: ${{ github.event_name != 'pull_request' }}
