name: 'Container Build and Publish'
description: 'GitHub Action with a pipeline to build, test and publish a container image'
inputs:
  workdir:
    description: "Working directory of bake execution"
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Check the Containerfile with hadolint
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        $(git rev-parse --show-toplevel)/bin/lint.sh
